### PR TITLE
[Support] Branch linting

### PR DESCRIPTION
**Pull request by Azoraqua**
Adds a workflow for branch linting; Preventing users from pushing, or creating a pull-request that do not follow the branch naming conventions.

Proposed conventions:
- `master`
- `develop`
- `release/[v][release][.major][.minor]`
- `feature/[name_with_underscores_or_dashes]`
- `bugfix/[name_with_underscores_or_dashes]`
- `support/[name_with_underscores_or_dashes]`

**Note:** The branches that dependabot creates are also validated, these are specific to dependabot and should not be used by people in general.

### CODE REVIEW

**Review by 0xLeif — APPROVED** [review]

**Review by aayushchugh — COMMENTED** [review]
@Azoraqua  It would be great if we have a rule for 

`refactor/name`

**Comment by aayushchugh** [comment]
another convention that we can follow is 
`{username}/{issue_number}` like `aayushchugh/40`
and require everyone to create an issue first than create a branch for that issue
it is used if you use GitHub extension in vscode

**Comment by Azoraqua** [comment]
> @Azoraqua It would be great if we have a rule for
> 
> `refactor/name`

The conventions are based on the Git Flow principle, in case of refactors; It can be put under either of the four groups. 
Most likely `release` if it's a major refactor or `support` if it's not a drastical change.

**Comment by Azoraqua** [comment]
> another convention that we can follow is 
`{username}/{issue_number}` like `aayushchugh/40`
and require everyone to create an issue first than create a branch for that issue
it is used if you use GitHub extension in vscode

Regarding this, I personally don't like to associate anything with a specific user, but rather put in a broader manner. From the perspective of the project itself.

Besides, not every issue is about code itself; it can be a simple question or suggestion which doesn't really have anything to be associated with in code.

**Review by aayushchugh — APPROVED** [review]

**Comment by Azoraqua** [comment]
Bytheway, a note to the person that is going to merge it (Which may be myself); Squash the commits into one and merge them.

image

**Comment by aayushchugh** [comment]
@Azoraqua title should be the PR title right?

**Pull request merged**
