### PR TITLE
add custom carousel feature to CarouselWrapper for more control

### PR DESCRIPTION
**Pull request by vutran6853**

### CODE REVIEW

**Comment by zmeriksen** [comment]
#17

**Comment by will-nemo** [comment]
PR review from my phone lol but for the CarouselWrapper.js we’re trying to stick to hooks rather than class components https://reactjs.org/docs/hooks-intro.html if you haven’t worked with those it gets rid of some early issues that react was having and the recommended way to do it. Also you could rename the file since it’s no longer a wrapper

**Comment by will-nemo** [comment]
Also if you could pass omg the “imgs” and the interval as a prop so we can get customizable with it and make make the Img jsx so we could pass whatever we wanted to it, even html

**Comment by zmeriksen** [comment]
Any update on this? Looking stale...

**Comment by zmeriksen** [comment]
Closing since stale new [PR](https://github.com/oneleif/olWebsite-React/pull/19)

**Pull request closed without merging**
