### PR TITLE
focus to a.button

### PR DESCRIPTION
**Pull request by cosmin-mihalache**
I added &focus to a.button with blue color from links.
Or I could add directly to the primary: -&hover
                                                              -&active
                                                              -&focus

### CODE REVIEW

**Comment by will-nemo** [comment]
> I added &focus to a.button with blue color from links.
> Or I could add directly to the primary: -&hover
> -&active
> -&focus

on the a.button is perfect. I will say yes that adds an outline but we'd like it to resemble the outline shown in the image on the ticket.

```outline: -webkit-focus-ring-color auto 5px;``` 
^^^ is how it's handled on a normal button on focus, just doesn't seem to do that on links for some reason,

**Comment by cosmin-mihalache** [comment]
> Try your best and make it look like how screen shot on the ticket. We may have to ask around cause this might be an anti pattern that we're just trying to break lol

Ok. I'm gonna ask around.

**Comment by will-nemo** [comment]
From what I discussed online it seems like a link is a link so it should act like a link. Even if you click around all the "buttons" on github you can see they are all links and don't have that outline we want. We can OBE/Close this ticket and have a discussion on links vs buttons for our website

**Comment by cosmin-mihalache** [comment]
Ah. Ok. 
Also for the firefox, the inputs don't have focus or I can't see it lol, probably depends on how is the default setup of the browsers.

**Pull request closed without merging**
