### PR TITLE
Corrected the spelling

### PR DESCRIPTION
**Pull request by Gautam-Arora24**

### CODE REVIEW

**Comment by Gautam-Arora24** [comment]
Kindly let me know about this Commit?

**Comment by 0xLeif** [comment]
@Gautam-Arora24 It looks good to me! I'm waiting for @will-nemo to give it a look as he is the lead on this project.

**Review by 0xLeif — APPROVED** [review]

**Comment by Gautam-Arora24** [comment]
Thanks @0xLeif

**Review by will-nemo — APPROVED** [review]

**Comment by Gautam-Arora24** [comment]
Hey @0xLeif I want to work for this organisation and contribute. How can I do that?

**Pull request merged**
