### PR TITLE
Update Selector/Link Styling

### PR DESCRIPTION
**Pull request by will-nemo**

### CODE REVIEW

**Comment by will-nemo** [comment]
> Looks good. I did notice though that because the buttons on the PageNotFound and ContactUS pages are a tags instead of buttons, there is no border/outline applied to them like the join button on the Landing.
 
Ah good catch, i looked into this. It seems to be an unrelated bug since these are links they don't have the :focus on click for some reason, we might need to make a ticket for this take it on somehow to add this outline ourselves

**Comment by Fabricevladimir** [comment]
> > Looks good. I did notice though that because the buttons on the PageNotFound and ContactUS pages are a tags instead of buttons, there is no border/outline applied to them like the join button on the Landing.
> 
> Ah good catch, i looked into this. It seems to be an unrelated bug since these are links they don't have the :focus on click for some reason, we might need to make a ticket for this take it on somehow to add this outline ourselves

We should be able to just add that to the base button class CSS, yes?

**Comment by b1995** [comment]
> Looks good. I did notice though that because the buttons on the PageNotFound and ContactUS pages are a tags instead of buttons, there is no border/outline applied to them like the join button on the Landing.

The privacy policy and terms&conditions at the buttom of the page are also not getting any effects on them. They appear to be a tags as well.

**Comment by will-nemo** [comment]
> > > Looks good. I did notice though that because the buttons on the PageNotFound and ContactUS pages are a tags instead of buttons, there is no border/outline applied to them like the join button on the Landing.
> > 
> > 
> > Ah good catch, i looked into this. It seems to be an unrelated bug since these are links they don't have the :focus on click for some reason, we might need to make a ticket for this take it on somehow to add this outline ourselves
> 
> We should be able to just add that to the base button class CSS, yes?

I've tried this and haven't seen any effect so I'm not sure. Feel free to pull it down and let me know if you see it.

**Comment by will-nemo** [comment]
> > Looks good. I did notice though that because the buttons on the PageNotFound and ContactUS pages are a tags instead of buttons, there is no border/outline applied to them like the join button on the Landing.
> 
> The privacy policy and terms&conditions at the buttom of the page are also not getting any effects on them. Unless this is not supposed to effect them?

That's expected behavior at this point

**Pull request merged**
