### PR TITLE
ci: :memo: added issue templates

### LINKED ISSUE #280: ci: Add issue templates
currently there are no issue templates in this repo
I think we should add some

here is example of issue templates I can add in this repo:-
https://github.com/shriproperty/server/issues/new/choose

### PR DESCRIPTION
**Pull request by aayushchugh**
closes #280

created issue templates

example:- https://github.com/shriproperty/server/issues/new/choose

### CODE REVIEW

**Review by 0xLeif — APPROVED** [review]
Amazing! 🤩

**Comment by aayushchugh** [comment]
@0xLeif Please check the descriptions I can change them if you want

**Comment by 0xLeif** [comment]
> @0xLeif Please check the descriptions I can change them if you want

I think they are fine for now! We can update them later. 😊

**Comment by 0xLeif** [comment]
I'll let someone else approve this PR... they might suggest something.

**Review by haIIux — COMMENTED** [review]
It looks good to me! I like them!

**Review by haIIux — APPROVED** [review]

**Comment by aayushchugh** [comment]
should I delete this branch ?

**Comment by haIIux** [comment]
I couldn't click the merge button fast enough - Ronald beat me to the punch! 👊🏼  😄

**Comment by aayushchugh** [comment]
image

**Pull request merged**
