### PR TITLE
Release v1.2.0

### LINKED ISSUE #285: Update the project.
### Description

Goals:
- [x] #286
- [x] #287
- [x] #288
- [x] #289

### Anything else?

- [TypeScript](https://www.typescriptlang.org/)
- [Vite](https://vitejs.dev/)
- [MaterialUI](https://mui.com/)

### LINKED ISSUE #286: Add TypeScript (TS)

### LINKED ISSUE #287: Replace Create React App (CRA) with Create Vite App (Vite)

### LINKED ISSUE #288: Use an UI toolkit (To be discussed, defaulting to MaterialUI)

### LINKED ISSUE #289: Update additional dependencies and remove unneccessary ones.

### PR DESCRIPTION
**Pull request by Azoraqua**

### CODE REVIEW

**Review by aayushchugh — APPROVED** [review]
image

I don't have courage to review these many changes so I will just approve them

**Comment by haIIux** [comment]
It's likely not good practice to blindly approve without actually taking a look to review and provide feedback if needed.

**Comment by aayushchugh** [comment]
> It's likely not good practice to blindly approve without actually taking a look to review and provide feedback if needed.

I actually saw the code in vscode he just created backup of src and public and initialized vite 
just did that for fun

**Review by Azoraqua — COMMENTED** [review]
May I suggest to remove .vscode and put it in a .gitignore.

Beyond that, I like to call the folders like:
- components
- hooks
- models
- reducers
- routers
- contexts
- helpers / utils
- ...

**Pull request closed without merging**
