### PR TITLE
Create filter box container

### PR DESCRIPTION
**Pull request by will-nemo**
Created a simple border container to help organize the page a bit more styling wise. Also did my best to make it responsive.

### CODE REVIEW

**Comment by will-nemo** [comment]
#51

**Comment by Fabricevladimir** [comment]
I noticed that a lot of the components only render children and assign the proper class name. Should we have a generic container component instead that takes in the class name as props?

**Comment by will-nemo** [comment]
> I noticed that a lot of the components only render children and assign the proper class name. Should we have a generic container component instead that takes in the class name as props?

Right now these are all basic containers since there isn't really any functionality or styling that will change. I have thought about having a basic container but that might become an issue in the future with readability.

An example of this would be with our generic card. Yes all the pieces are the same but if they were just a container with the className passed in it would look like:

```
<Container>
    <Container>
       //Children
    </Container>
    <Container>
       //children
     </Container>
</Container
```

rather than 

```
<CardContainer>
   <CardHeader>
     //children
   </CardHeader>
   <CardContent>
     //Children
   </CardContent>
</CardContainer>
```

**Comment by Fabricevladimir** [comment]
I see what you mean about the generic container. A potential solution though could be to export the one generic container function with different aliases like below. It's sort of a hack and not as elegant, but I believe it is still a viable solution.

```javascript
 export {
   Container as CardHeader,
   Container as CardFooter
 };
```

**Comment by will-nemo** [comment]
That makes sense, can you import like that? Never seen it done. But these were created in hope of having some sort of base styling with a className passed down to change the type of card. Just don't have any styling at this point so that's why it's so basic

**Comment by Fabricevladimir** [comment]
It is possible to export them like that. In turn, they wold be imported like so:

```javascript
import { CardHeader, Cardfooter} from '. /GenericContainer' ;
```
In fact we could bypass this hack and just import the same component just named differently. 

```javascript
import CardHeader from '. /GenericContainer' ;
import CardFooter from '. /GenericContainer' ;
```
If those individual containers are going to change though, then I guess we can go ahead and keep them.

**Pull request merged**
